membersrvc:
  image: hyperledger/fabric-membersrvc
  ports:
    - "7054:7054"
  volumes: 
    - /var/run/docker.sock:/var/run/docker.sock
  command: membersrvc
vp0:
  image: hyperledger/fabric-peer
  ports:
    - "7050:7050"
    - "7051:7051"
    - "7052:7052"
  environment:
    - CORE_PEER_ADDRESSAUTODETECT=true
    - CORE_LOGGING_LEVEL=DEBUG
    - CORE_PEER_ID=vp0
    - CORE_SECURITY_ENROLLID=test_vp0
    - CORE_SECURITY_ENROLLSECRET=MwYpmSRjupbT
    - CORE_PEER_VALIDATOR_CONSENSUS_PLUGIN=pbft  # noops, pbft
    - CORE_PBFT_GENERAL_MODE=batch  # batch. classic and sieve will be not supported again.
    - CORE_PBFT_GENERAL_N=4
    - CORE_PBFT_GENERAL_BATCHSIZE=2  # only useful when in batch mode
    - CORE_PBFT_GENERAL_TIMEOUT_REQUEST=2s
  volumes:
    - $GOPATH/src/github.com/hyperledger/fabric/examples/chaincode:/opt/gopath/src/github.com/hyperledger/fabric/examples/chaincode
    - /var/run/docker.sock:/var/run/docker.sock
  links:
    - membersrvc
  command: sh -c "sleep 5; peer node start"
vp1:
  image: hyperledger/fabric-peer
  environment:
    - CORE_PEER_ADDRESSAUTODETECT=true
    - CORE_LOGGING_LEVEL=DEBUG
    - CORE_PEER_ID=vp1
    - CORE_PEER_DISCOVERY_ROOTNODE=vp0:7051
    - CORE_SECURITY_ENROLLID=test_vp1
    - CORE_SECURITY_ENROLLSECRET=5wgHK9qqYaPy
    - CORE_PEER_VALIDATOR_CONSENSUS_PLUGIN=pbft  # noops, pbft
    - CORE_PBFT_GENERAL_MODE=batch  # batch. classic and sieve will be not supported again.
    - CORE_PBFT_GENERAL_N=4
    - CORE_PBFT_GENERAL_BATCHSIZE=2  # only useful when in batch mode
    - CORE_PBFT_GENERAL_TIMEOUT_REQUEST=2s
  volumes: 
    - /var/run/docker.sock:/var/run/docker.sock
    - $GOPATH/src/github.com/hyperledger/fabric/examples/chaincode:/opt/gopath/src/github.com/hyperledger/fabric/examples/chaincode
  links:
    - membersrvc
    - vp0
  command: sh -c "sleep 5; peer node start"
vp2:
  image: hyperledger/fabric-peer
  environment:
    - CORE_PEER_ADDRESSAUTODETECT=true
    - CORE_LOGGING_LEVEL=DEBUG
    - CORE_PEER_ID=vp
    - CORE_PEER_DISCOVERY_ROOTNODE=vp0:7051
    - CORE_SECURITY_ENROLLID=test_vp2
    - CORE_SECURITY_ENROLLSECRET=vQelbRvja7cJ
    - CORE_PEER_VALIDATOR_CONSENSUS_PLUGIN=pbft  # noops, pbft
    - CORE_PBFT_GENERAL_MODE=batch  # batch. classic and sieve will be not supported again.
    - CORE_PBFT_GENERAL_N=4
    - CORE_PBFT_GENERAL_BATCHSIZE=2  # only useful when in batch mode
    - CORE_PBFT_GENERAL_TIMEOUT_REQUEST=2s
  volumes: 
    - /var/run/docker.sock:/var/run/docker.sock
    - $GOPATH/src/github.com/hyperledger/fabric/examples/chaincode:/opt/gopath/src/github.com/hyperledger/fabric/examples/chaincode
  links:
    - membersrvc
    - vp0
  command: sh -c "sleep 5; peer node start"
vp3:
  image: hyperledger/fabric-peer
  environment:
    - CORE_PEER_ADDRESSAUTODETECT=true
    - CORE_LOGGING_LEVEL=DEBUG
    - CORE_PEER_ID=vp3
    - CORE_PEER_DISCOVERY_ROOTNODE=vp0:7051
    - CORE_SECURITY_ENROLLID=test_vp3
    - CORE_SECURITY_ENROLLSECRET=9LKqKH5peurL
    - CORE_PEER_VALIDATOR_CONSENSUS_PLUGIN=pbft  # noops, pbft
    - CORE_PBFT_GENERAL_MODE=batch  # batch. classic and sieve will be not supported again.
    - CORE_PBFT_GENERAL_N=4
    - CORE_PBFT_GENERAL_BATCHSIZE=2  # only useful when in batch mode
    - CORE_PBFT_GENERAL_TIMEOUT_REQUEST=2s
  volumes: 
    - /var/run/docker.sock:/var/run/docker.sock
    - $GOPATH/src/github.com/hyperledger/fabric/examples/chaincode:/opt/gopath/src/github.com/hyperledger/fabric/examples/chaincode
  links:
    - membersrvc
    - vp0
  command: sh -c "sleep 5; peer node start"

